// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn96ZJj8v90v2oE8-Iw0ASuA-NOfmUGc8',
    appId: '1:486377492368:web:8bf04ebdc9bc6029b26d15',
    messagingSenderId: '486377492368',
    projectId: 'watchify-a9d41',
    authDomain: 'watchify-a9d41.firebaseapp.com',
    storageBucket: 'watchify-a9d41.firebasestorage.app',
    measurementId: 'G-6F8FTEXGS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHottMkrvSb1pDZWwA9l01-HvqZq3d-fc',
    appId: '1:486377492368:android:b4158a70c1ddb542b26d15',
    messagingSenderId: '486377492368',
    projectId: 'watchify-a9d41',
    storageBucket: 'watchify-a9d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPF-Bj0IH2K2l_D1nOeaiq1AJ32PIYHCA',
    appId: '1:486377492368:ios:e3126c5b3b3aec78b26d15',
    messagingSenderId: '486377492368',
    projectId: 'watchify-a9d41',
    storageBucket: 'watchify-a9d41.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPF-Bj0IH2K2l_D1nOeaiq1AJ32PIYHCA',
    appId: '1:486377492368:ios:e3126c5b3b3aec78b26d15',
    messagingSenderId: '486377492368',
    projectId: 'watchify-a9d41',
    storageBucket: 'watchify-a9d41.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );
}
